# Dependencies
baseurl:          /
url:              http://zhenzhoupang.com
markdown            : kramdown
redcarpet:
  extensions        : ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter         : rouge
gems                : ["jekyll-paginate"]
# Permalinks
permalink:        pretty

# Setup
title:            Pang
tagline:          'A Jekyll theme forks https://github.com/poole/hyde'
description:      '技术.思考.生活'

author:
  name:           'pangzhenzhou'
  #url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.0.9

github:
  repo:           https://github.com/pangzhenzhou
gems:
  - jemoji
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-sitemap
